alias RoNet="cd /media/kurt/UUI/RoNet_2017"
alias sticky="cd /media/kurt/UUI/RoNet_2017"
alias speicher="free; df -h /home"
alias intranet="cd /var/www/html"
alias  q="exit"
alias programmieren="cd ~/RoNet/programmieren"
alias Studium="cd ~/RoNet/Studium"
alias grundkurs_c="evince ~/Dokumente/grundkurs-c.pdf"
alias C_programmierung="cd ~/RoNet/programmieren/c"
alias skripte="cd ~/RoNet/skripte"
alias grundkurs_latex="evince ~/Dokumente/grundkurs-latex.pdf"
alias anleitungen="cd ~/RoNet/anleitungen"
alias texte="cd ~/RoNet/texte"
# alias magenta="cd /run/user/1002/gvfs/'dav:host=webdav.magentacloud.de,ssl=tru'"
alias datenbanken="cd ~/RoNet/datenbanken"
alias magenta="cd /run/user/1002/gvfs/dav\:host\=webdav.magentacloud.de\,ssl\=true/"
alias pdf="echo Bitte mit evince aufrufen ..." 
